[package]
name = "tagbinding_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "rs_tags"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module"] }
tagcore = { path = "../tagcore" }